# Theme settings
doks:
    baseurl: MT-jekyll-test/
    color_theme: blue # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: Metrics Toolkit
            image:
        nav:
            - item_name: Home
              item_url: 'https://coateshl.github.io/MT-jekyll-test/index'
            - item_name: Choose Metrics
              item_url: 'https://coateshl.github.io/MT-jekyll-test/choose'
            - item_name: Resources
              item_url: 'https://coateshl.github.io/MT-jekyll-test/resources'
            - item_name: About
              item_url: 'https://coateshl.github.io/MT-jekyll-test/about'
            - item_name: Schema
              item_url: 'https://coateshl.github.io/MT-jekyll-test/schema'

              
    footer:
        content:
            logo: 
                text: 
                image: 
            copyright: This site is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)
        social_list: 
            - network_name: GitHub
              profile_url: https://github.com/Metrics-Toolkit

    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics - UA-139939429-1
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
